package WWTP.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myNode__BehaviorDescriptor = new Node__BehaviorDescriptor();
  private final BHDescriptor mySensor_Type__BehaviorDescriptor = new Sensor_Type__BehaviorDescriptor();
  private final BHDescriptor myHopper__BehaviorDescriptor = new Hopper__BehaviorDescriptor();
  private final BHDescriptor myMec_Dehydration__BehaviorDescriptor = new Mec_Dehydration__BehaviorDescriptor();
  private final BHDescriptor mySludge_Thickener__BehaviorDescriptor = new Sludge_Thickener__BehaviorDescriptor();
  private final BHDescriptor myContainer__BehaviorDescriptor = new Container__BehaviorDescriptor();
  private final BHDescriptor myRegion__BehaviorDescriptor = new Region__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myContainer__BehaviorDescriptor;
      case 1:
        return myHopper__BehaviorDescriptor;
      case 2:
        return myMec_Dehydration__BehaviorDescriptor;
      case 3:
        return myNode__BehaviorDescriptor;
      case 4:
        return myRegion__BehaviorDescriptor;
      case 5:
        return mySensor_Type__BehaviorDescriptor;
      case 6:
        return mySludge_Thickener__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x330981c29fe0fb09L), MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x2f0319829866568bL), MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x2f03198298b466deL), MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x23381bd32c685983L), MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x6175b41c53adc15cL), MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x23381bd32c6859b3L), MetaIdFactory.conceptId(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x2f03198298e88fe3L)).seal();
}
