apiVersion: v1
kind: Pod
metadata:
  name: c-mosquitto
  labels:
    app: brokerMQTT
spec:
  containers:
    - name: c-mosquitto
      image: eclipse-mosquitto:2.0
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
        requests:
          memory: "500Mi"
          cpu: "500m"
      ports:
      - containerPort: 1883
      volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
  volumes:
  - name: mosquitto-config
    configMap:
      name: mosquitto-config
  nodeSelector:
    node: edge-node-1
---
apiVersion: v1
kind: Pod
metadata:
  name: realtime-app
  labels:
    app: realtimeAnalysis
spec:
  containers:
    - name: realtime-app
      image: realtime-app:latest
      resources:
        limits:
          cpu: "1m"
        requests:
          memory: "600Mi"
          cpu: "500m"
      ports:
      - containerPort: 8080



  nodeSelector:
    node: fog-node-1
---
