apiVersion: v1
kind: Pod
metadata:
  name: mosquitto
  labels:
    app: broker
spec:
  containers:
    - name: mosquitto
      image: eclipse-mosquitto:2.0
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
        requests:
          memory: "500Mi"
          cpu: "500m"
      ports:
      - containerPort: 1883
      volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
  volumes:
  - name: mosquitto-config
    configMap:
      name: mosquitto-config
  nodeSelector:
    node: edge-node
---
