apiVersion: v1
kind: Service
metadata:
  name: broker-mqtt-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: broker-mqtt
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30070
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-analysis-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: realtime-analysis
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
---
