apiVersion: v1
kind: Service
metadata:
  name: brokerMQTT-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: brokerMQTT
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30070
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeAnalysis-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: realtimeAnalysis
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
---
