apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-exporter-config
  namespace: monitoring
data:
  conf.yaml: |
    # MQTT All values default to paho.mqtt.client defaults
    mqtt:
      host:      'som-research.uoc.edu'
      port:       443

    metrics:
      - name:     'wwtp_GChamber_ph'
        help:     'Topic wwtp/GChamber/ph'
        type:     'gauge'
        topic:    'wwtp/GChamber/ph'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_cond'
        help:     'Topic wwtp/GChamber/cond'
        type:     'gauge'
        topic:    'wwtp/GChamber/cond'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_cod'
        help:     'Topic wwtp/GChamber/cod'
        type:     'gauge'
        topic:    'wwtp/GChamber/cod'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_tss'
        help:     'Topic wwtp/GChamber/tss'
        type:     'gauge'
        topic:    'wwtp/GChamber/tss'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_temp'
        help:     'Topic wwtp/GChamber/temp'
        type:     'gauge'
        topic:    'wwtp/GChamber/temp'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_toc'
        help:     'Topic wwtp/GChamber/toc'
        type:     'gauge'
        topic:    'wwtp/GChamber/toc'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_valve'
        help:     'Topic wwtp/GChamber/valve'
        type:     'gauge'
        topic:    'wwtp/GChamber/valve'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'wwtp_GChamber_buzzer'
        help:     'Topic wwtp/GChamber/buzzer'
        type:     'gauge'
        topic:    'wwtp/GChamber/buzzer'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'
