package Shapes.blocks;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Shape;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Area;

public class Bio_Reactor extends AbstractShape {


  public Bio_Reactor() {
  }


  @Override
  public Shape getShape(final Rectangle2D bounds) {
    Area area = new Area();
    Rectangle2D.Double rect = new Rectangle2D.Double(bounds.getX(), bounds.getY() + 60, bounds.getWidth(), bounds.getHeight());
    Rectangle2D.Double line = new Rectangle2D.Double(bounds.getX() + 3, bounds.getY() + 50 + bounds.getHeight(), bounds.getWidth() - 6, 5);
    area.add(new Area(rect));
    area.subtract(new Area(line));
    return area;
  }



}
