package Shapes.blocks;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Shape;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;

public class Decanter extends AbstractShape {


  public Decanter() {
  }


  @Override
  public Shape getShape(final Rectangle2D bounds) {
    Area area = new Area();
    double w = bounds.getWidth();
    double h = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    Rectangle2D.Double rect = new Rectangle2D.Double(x, y + 60, w, h);
    Ellipse2D.Double obj = new Ellipse2D.Double(x + (w * 2 / 5), y + 60 + (h - (h / 8)), w / 5, h / 4);
    Rectangle2D.Double line1 = new Rectangle2D.Double(x - 2 + w / 2, y + 62, 4, h - 4);
    Rectangle2D.Double line2 = new Rectangle2D.Double(x - 2 + w * 4 / 6, y + 62, 4, h - 4);
    Rectangle2D.Double line3 = new Rectangle2D.Double(x - 2 + w * 5 / 6, y + 62, 4, h - 4);
    area.add(new Area(rect));
    area.add(new Area(obj));
    area.subtract(new Area(line1));
    area.subtract(new Area(line2));
    area.subtract(new Area(line3));
    return area;
  }



}
