package Shapes.blocks;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Shape;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Area;
import java.awt.geom.Arc2D;

public class GritChamber extends AbstractShape {


  public GritChamber() {
  }


  @Override
  public Shape getShape(final Rectangle2D bounds) {
    Area area = new Area();
    double w = bounds.getWidth();
    double h = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    Rectangle2D.Double rect = new Rectangle2D.Double(x + 10, y + 60, w - 20, h);
    Arc2D.Double arc1 = new Arc2D.Double(x - w / 2, y + 60 + h * 2 / 3, w, h, 90, 270, 0);
    Arc2D.Double arc2 = new Arc2D.Double(x + w / 2, y + 60 + h * 2 / 3, w, h, 180, 270, 0);
    area.add(new Area(rect));
    area.subtract(new Area(arc1));
    area.subtract(new Area(arc2));

    return area;
  }



}
