package Shapes.blocks;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Shape;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;

public class Hopper extends AbstractShape {


  public Hopper() {
  }


  @Override
  public Shape getShape(final Rectangle2D bounds) {
    Area area = new Area();
    double w = bounds.getWidth();
    double h = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    Rectangle2D.Double rect = new Rectangle2D.Double(x, y + 60, w, h * 2 / 3);
    Ellipse2D.Double ellip = new Ellipse2D.Double(x, y + 60 + (h / 3), w, h / 2);
    Rectangle2D.Double line_l = new Rectangle2D.Double(x, y + 60 + h * 2 / 3, 3, h / 2);
    Rectangle2D.Double line_r = new Rectangle2D.Double(w + x - 3, y + 60 + h * 2 / 3, 3, h / 2);
    area.add(new Area(rect));
    area.add(new Area(ellip));
    area.add(new Area(line_l));
    area.add(new Area(line_r));
    return area;
  }



}
