package Shapes.blocks;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import de.itemis.mps.editor.diagram.runtime.shape.IShapeStyle;
import java.awt.geom.GeneralPath;
import java.awt.Color;

public class IconWaterFlow extends AbstractShape {


  public IconWaterFlow() {
  }




  @Override
  protected void draw(final Graphics2D graphics, final Rectangle2D bounds, IShapeStyle style) {
    GeneralPath shape = new GeneralPath();
    double w = bounds.getWidth();
    double h = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    shape.moveTo(x, y + h - 2);
    shape.lineTo(x + (w / 2) + 1, y + h - 2);
    shape.lineTo(x + (w / 2) + 1, y + 4);
    shape.lineTo(x + w, y + 4);
    shape.lineTo(x + w, y + 2);
    shape.lineTo(x + (w / 2) - 1, y + 2);
    shape.lineTo(x + (w / 2) - 1, y + h - 4);
    shape.lineTo(x, y + h - 4);
    shape.closePath();
    graphics.setColor(Color.BLUE);
    graphics.fill(shape);
  }

}
