apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alert-High conductivity alarm
      interval: 1s
      rules:
      - alert: High conductivity alarm
        # Condition for alerting
        expr: wwtp_GChamber_cond > 5000
        for: 2m
        annotations:
          adaptations: '{"operate_actuator_0.2396376150791143":{"broker_ip":"som-research.uoc.edu","port":443,"topic":"wwtp/GChamber/valve","message":"on"}}'
        labels:
          severity: 'critical'
          actions: '0'

    - name: Alert-High TTS alarm
      interval: 1s
      rules:
      - alert: High TTS alarm
        # Condition for alerting
        expr: wwtp_GChamber_tss > 1000
        for: 2m
        annotations:
          adaptations: '{"operate_actuator_0.6532723081216287":{"broker_ip":"som-research.uoc.edu","port":443,"topic":"wwtp/GChamber/buzzer","message":"on"}}'
        labels:
          severity: 'critical'
          actions: '0'

    - name: Alert-High COD alarm
      interval: 1s
      rules:
      - alert: High COD alarm
        # Condition for alerting
        expr: wwtp_GChamber_cod > 1500
        for: 2m
        annotations:
          adaptations: '{"operate_actuator_0.9961196661669722":{"broker_ip":"som-research.uoc.edu","port":443,"topic":"wwtp/GChamber/valve","message":"on"}}'
        labels:
          severity: 'critical'
          actions: '0'

    - name: Alert-High temperature alarm
      interval: 1s
      rules:
      - alert: High temperature alarm
        # Condition for alerting
        expr: wwtp_GChamber_temp > 50
        for: 2m
        annotations:
          adaptations: '{"operate_actuator_0.7332576734386149":{"broker_ip":"som-research.uoc.edu","port":443,"topic":"wwtp/GChamber/buzzer","message":"on"}}'
        labels:
          severity: 'critical'
          actions: '0'

    - name: Alert-pH alarm
      interval: 1s
      rules:
      - alert: pH alarm
        # Condition for alerting
        expr: wwtp_GChamber_ph < 6 or wwtp_GChamber_ph > 9
        for: 2m
        annotations:
          adaptations: '{"operate_actuator_0.7112724631684801":{"broker_ip":"som-research.uoc.edu","port":443,"topic":"wwtp/GChamber/buzzer","message":"on"}}'
        labels:
          severity: 'critical'
          actions: '0'
