apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alert-GC-level Alarm
      interval: 1s
      rules:
      - alert: GC-level Alarm
        # Condition for alerting
        expr: wwtp_level > 400
        for: 50s
        annotations:
          adaptations: '{"operate_actuator_0.0872584705149565":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/valve","message":"open"},"operate_actuator_0.8010238045052724":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/buzzer1","message":"on"}}'
        labels:
          severity: 'critical'
          actions: 'all'

    - name: Alert-GC-EConductivity Alarm
      interval: 1s
      rules:
      - alert: GC-EConductivity Alarm
        # Condition for alerting
        expr: (wwtp_ec1 or wwtp_ec2) > 2500
        for: 10m
        annotations:
          adaptations: '{"operate_actuator_0.9226002733987007":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/buzzer1","message":"on"},"operate_actuator_0.027974350478626064":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/buzzer2","message":"on"}}'
        labels:
          severity: 'critical'
          actions: '0'

    - name: Alert-CPU high consumption
      interval: 1s
      rules:
      - alert: CPU high consumption
        # Condition for alerting
        expr: 100 - (avg by(node_hostname) (rate(node_cpu_seconds_total{mode="idle",node_hostname="fog-node-1"}[35s])) * 100) > 80
        for: 2m
        annotations:
          adaptations: '{"offloading_0.5465681366993159":{"pod_name":"realtime-app","image":"realtime-app:latest","namespace":"default","requirements":{"memory":"600M","cpu":"500m"},"volumes":[],"hosts":{"node":{"operator":"In","values":["edge-node-1"]},"region":{"operator":"In","values":[]},"cluster":{"operator":"In","values":[]}}}}'
        labels:
          severity: 'critical'
          actions: '0'
