apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alert-GC-level Alarm
      interval: 1s
      rules:
      - alert: GC-level Alarm
        # Condition for alerting
        expr: wwtp_level > 400
        for: 5m
        annotations:
          adaptations: '{"operate_actuator":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/valve",
                        "message":"open"},"operate_actuator_0.4650132056856807":{"broker_ip":"3.223.97.169",
                        "port":30070,"topic":"wwtp/buzzer","message":"on"}}'
        labels:
          severity: 'critical'
          actions: 'all'
