apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alert-Temperature - led
      interval: 1s
      rules:
      - alert: Temperature - led
        # Condition for alerting
        expr: wwtp_temperature > 30
        for: 10s
        annotations:
          adaptations: '{"operate_actuator_0.7102920479619731":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/led","message":"1"}}'
        labels:
          severity: 'critical'
          actions: 'all'

    - name: Alert-Temperature - buzzer
      interval: 1s
      rules:
      - alert: Temperature - buzzer
        # Condition for alerting
        expr: wwtp_temperature > 30
        for: 20s
        annotations:
          adaptations: '{"operate_actuator_0.762013355153403":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/buzzer","message":"1"}}'
        labels:
          severity: 'critical'
          actions: 'all'

    - name: Alert-Led/Buzzer off
      interval: 1s
      rules:
      - alert: Led/Buzzer off
        # Condition for alerting
        expr: wwtp_temperature < 30
        for: 5s
        annotations:
          adaptations: '{"operate_actuator_0.506900731240578":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/led","message":"0"},"operate_actuator_0.24984743108612695":{"broker_ip":"3.223.97.169","port":30070,"topic":"wwtp/buzzer","message":"0"}}'
        labels:
          severity: 'critical'
          actions: 'all'
