apiVersion: v1
kind: Pod
metadata:
  name: pod-broker
  labels:
    app: broker-mqtt
spec:
  containers:
    - name: pod-broker
      image: eclipse-mosquitto:2.0
      resources:

        requests:
          memory: "500Mi"
          cpu: "500m"
      ports:
      - containerPort: 1883



  nodeSelector:
    node: cloud-node
---
