apiVersion: v1
kind: Service
metadata:
  name: broker-mqtt-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: broker-mqtt
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30070
---
apiVersion: v1
kind: Service
metadata:
  name: spill-predictor-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: spill-predictor
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30090
---
