package WWTP.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Actuator = 1;
  public static final int Actuator_Type = 2;
  public static final int AdaptationRule = 3;
  public static final int Application = 4;
  public static final int Bio_Reactor = 5;
  public static final int Cloud_Node = 6;
  public static final int Cluster = 7;
  public static final int Cluster_Reference = 8;
  public static final int Container = 9;
  public static final int Container_Reference = 10;
  public static final int Decanter = 11;
  public static final int Edge_Node = 12;
  public static final int Exp_LayerReg = 13;
  public static final int Filtrator = 14;
  public static final int Fog_Node = 15;
  public static final int Grammar = 16;
  public static final int Grit_Chamber = 17;
  public static final int Hopper = 18;
  public static final int IoT_Device = 19;
  public static final int IoT_Device_Reference = 20;
  public static final int IoT_System = 21;
  public static final int List_Of_Metrics = 22;
  public static final int Mec_Dehydration = 23;
  public static final int Metric = 24;
  public static final int Node = 25;
  public static final int Node_Reference = 26;
  public static final int Num_Value = 27;
  public static final int Offloading = 28;
  public static final int Operate_Actuator = 29;
  public static final int Other_Process = 30;
  public static final int Period = 31;
  public static final int Plant = 32;
  public static final int QoSCluster = 33;
  public static final int QoSContainer = 34;
  public static final int QoSNode = 35;
  public static final int QoSRegion = 36;
  public static final int QoS_Event = 37;
  public static final int Redeployment = 38;
  public static final int Region = 39;
  public static final int Region_Reference = 40;
  public static final int Resource_Expression = 41;
  public static final int Roughing_System = 42;
  public static final int Scaling = 43;
  public static final int Sensor = 44;
  public static final int SensorEvent = 45;
  public static final int SensorTypeEvent = 46;
  public static final int Sensor_Actuator_Type = 47;
  public static final int Sensor_Type = 48;
  public static final int Sludge_Flow = 49;
  public static final int Sludge_Thickener = 50;
  public static final int Threshold_Value = 51;
  public static final int Topic = 52;
  public static final int Treatment = 53;
  public static final int Treatment_Event = 54;
  public static final int Ultraviolet = 55;
  public static final int Volume = 56;
  public static final int Water_Flow = 57;
  public static final int WorkerReference = 58;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x222ccd66f9d64014L, 0x8569354bddee8138L);
    builder.put(0xcbb176aba9dbdddL, Action);
    builder.put(0x23381bd32c6875cbL, Actuator);
    builder.put(0x23381bd32c6859b6L, Actuator_Type);
    builder.put(0xcbb176aba26b788L, AdaptationRule);
    builder.put(0x23381bd32c6857a6L, Application);
    builder.put(0x2f03198298b45365L, Bio_Reactor);
    builder.put(0x23381bd32c6859a8L, Cloud_Node);
    builder.put(0x23381bd32c6859a9L, Cluster);
    builder.put(0x11dabaab0c63700aL, Cluster_Reference);
    builder.put(0x330981c29fe0fb09L, Container);
    builder.put(0x624a077add314f9fL, Container_Reference);
    builder.put(0x2f03198297dca07bL, Decanter);
    builder.put(0x23381bd32c6859a6L, Edge_Node);
    builder.put(0x12549f92e66c4868L, Exp_LayerReg);
    builder.put(0x2f03198298e88fe1L, Filtrator);
    builder.put(0x23381bd32c6859a7L, Fog_Node);
    builder.put(0x530692400145291eL, Grammar);
    builder.put(0x2f03198298e88fe4L, Grit_Chamber);
    builder.put(0x2f0319829866568bL, Hopper);
    builder.put(0x23381bd32c687594L, IoT_Device);
    builder.put(0x13065eed5f79955cL, IoT_Device_Reference);
    builder.put(0x23381bd32c6857a2L, IoT_System);
    builder.put(0xcbb176abaac8ce9L, List_Of_Metrics);
    builder.put(0x2f03198298b466deL, Mec_Dehydration);
    builder.put(0xcbb176abaac8cedL, Metric);
    builder.put(0x23381bd32c685983L, Node);
    builder.put(0x11dabaab0c637009L, Node_Reference);
    builder.put(0x1edc553a9815ad11L, Num_Value);
    builder.put(0x250b6e3f27339aeL, Offloading);
    builder.put(0xde8316f4b5dd34dL, Operate_Actuator);
    builder.put(0x2f03198298e88fe5L, Other_Process);
    builder.put(0x78a15643faf7e388L, Period);
    builder.put(0x3071940349ee7875L, Plant);
    builder.put(0x5306924001b2832bL, QoSCluster);
    builder.put(0x12549f92e660b9ceL, QoSContainer);
    builder.put(0x5306924001c7aec1L, QoSNode);
    builder.put(0xcbb176ababbb082L, QoSRegion);
    builder.put(0xcbb176aba3d9f94L, QoS_Event);
    builder.put(0x11dabaab0c6371b7L, Redeployment);
    builder.put(0x6175b41c53adc15cL, Region);
    builder.put(0x424863e2f3693460L, Region_Reference);
    builder.put(0x5306924001a481deL, Resource_Expression);
    builder.put(0x2f03198298e88fdfL, Roughing_System);
    builder.put(0x11dabaab0c637001L, Scaling);
    builder.put(0x23381bd32c6875c5L, Sensor);
    builder.put(0xcbb176abacfab9fL, SensorEvent);
    builder.put(0x53069240016af7c7L, SensorTypeEvent);
    builder.put(0x23381bd32c6859b0L, Sensor_Actuator_Type);
    builder.put(0x23381bd32c6859b3L, Sensor_Type);
    builder.put(0x5ddae2cc739086b5L, Sludge_Flow);
    builder.put(0x2f03198298e88fe3L, Sludge_Thickener);
    builder.put(0x12549f92e66c48e4L, Threshold_Value);
    builder.put(0x624a077add07cc36L, Topic);
    builder.put(0x3c97f76cf72f67bfL, Treatment);
    builder.put(0x313eff4551584394L, Treatment_Event);
    builder.put(0x2f03198298e88fe2L, Ultraviolet);
    builder.put(0x1df32ba8689ddf66L, Volume);
    builder.put(0x7a9dc28334287adfL, Water_Flow);
    builder.put(0x6175b41c53adc1a5L, WorkerReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
